version: '3'
services:
  accountbook-client:
    image: charciavisual/accountbook-client:pre-release
    container_name: accountbook-client
    restart: always
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
  accountbook-server:
    image: charciavisual/accountbook-server:pre-release
    container_name: accountbook-server
    restart: always
    ports:
      - 4000:4000
    env_file:
      - ./server/.env
