name: 'Auto Reviewer'
on: pull_request_target

jobs:
  add-reviews:
    runs-on: ubuntu-18.04
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
